routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['reset' => false, 'verify' => false]);

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    // group menu resiko
    Route::prefix('risk')->group(function () {
        Route::post('/profile/list', 'Risk\ProfileController@list')->name('profile.list');
        Route::resource('profile', Risk\ProfileController::class);

        Route::post('/statement/tmp_list', 'Risk\StatementController@tmp_list')->name('statement.tmp_list');
        Route::post('/statement/list', 'Risk\StatementController@list')->name('statement.list');
        Route::resource('statement', Risk\StatementController::class);

        Route::post('/control/list', 'Risk\ControlController@list')->name('control.list');
        Route::resource('control', Risk\ControlController::class);

        Route::post('/response/list', 'Risk\ResponseController@list')->name('response.list');
        Route::resource('response', Risk\ResponseController::class);
    });

    // group menu kendali mutu
    Route::prefix('control')->group(function () {
        Route::post('/employee/list', 'Control\EmployeeController@list')->name('employee.list');
        Route::resource('employee', Control\EmployeeController::class);

        Route::post('/auditan/list', 'Control\AuditanController@list')->name('auditan.list');
        Route::resource('auditan', Control\AuditanController::class);

        Route::post('/planning/list', 'Control\AuditPlanController@list')->name('planning.list');
        Route::resource('planning', Control\AuditPlanController::class);

        Route::post('/execution/list', 'Control\ExecutionController@list')->name('execution.list');
        Route::resource('execution', Control\ExecutionController::class);

        Route::post('/assigment/list', 'Control\AssigmentController@list')->name('assigment.list');
        Route::resource('assigment', Control\AssigmentController::class);

        Route::post('/report/list', 'Control\ReportController@list')->name('report.list');
        Route::resource('report', Control\ReportController::class);
    });

    // group menu setting
    Route::prefix('setting')->group(function () {
        Route::post('/period/set_active', 'Setting\PeriodController@set_active');
        Route::post('/period/list', 'Setting\PeriodController@list')->name('period.list');
        Route::resource('period', Setting\PeriodController::class);

        Route::post('/possibility/list', 'Setting\PossibilityController@list')->name('possibility.list');
        Route::resource('possibility', Setting\PossibilityController::class);

        Route::post('/impact/list', 'Setting\ImpactController@list')->name('impact.list');
        Route::resource('impact', Setting\ImpactController::class);

        Route::post('/category/list', 'Setting\CategoryController@list')->name('category.list');
        Route::resource('category', Setting\CategoryController::class);

        Route::post('/risk_impact/list', 'Setting\RiskImpactController@list')->name('risk_impact.list');
        Route::resource('risk_impact', Setting\RiskImpactController::class);

        Route::get('riskmap', 'Setting\RiskmapController@index')->name('riskmap.index');

        Route::get('/satker/list_tree', 'Setting\SatkerController@list_tree')->name('satker.list_tree');
        Route::resource('satker', Setting\SatkerController::class);

        Route::post('/stakeholder/list', 'Setting\StakeholderController@list')->name('stakeholder.list');
        Route::resource('stakeholder', Setting\StakeholderController::class);

        Route::post('/cluster/item', 'Setting\ClusterController@get_item');
        Route::post('/cluster/list', 'Setting\ClusterController@list')->name('cluster.list');
        Route::put('/cluster/{cluster}', 'Setting\ClusterController@update');

        Route::post('/user/list', 'Setting\UserController@list')->name('user.list');
        Route::resource('user', Setting\UserController::class);
    });
});

// Quick search dummy route to display html elements in search dropdown (header search)
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

app/Models/Response.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Response extends Model
{
    protected $fillable = [
        'risk_profile_id', 'risk_statement_id', 'response', 'innovation', 'innovation_target', 'possibility', 'impact', 'score', 'priority', 'responsible', 'resource', 'deadline', 'indicator'
    ];

    public function risk_profile()
    {
        return $this->belongsTo(RiskProfile::class);
    }

    public function risk_statement()
    {
        return $this->belongsTo(RiskStatement::class);
    }
}

app/Http/Controllers/Risk/ControlController.php
<?php

namespace App\Http\Controllers\Risk;

use App\Http\Controllers\Controller;
use App\Models\Impact;
use App\Models\Management;
use App\Models\Possibility;
use App\Models\RiskControl;
use App\Models\RiskStatement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\DataTables;

class ControlController extends Controller
{
    private $page_title = 'Pengendalian Risiko';

    private function rules(Request $request, bool $isEdit)
    {
        $rules = [
            'control' => 'required|min:5|max:250',
            'possibility' => 'integer',
            'impact' => 'integer',
        ];

        return $rules;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $uker_id = 1;
        if (isset($request->uker_id)) {
            $uker_id = $request->uker_id;
        }
        $page_title = $this->page_title;
        $page_description = 'list data -> Periode ' . period()->period;
        $uker = Management::pluck('title', 'id');

        return view('pages.risk.control.index', compact('page_title', 'page_description', 'uker', 'uker_id'));
    }

    /**
     * Show the list of targets data.
     *
     * @return Yajra\Datatables\Datatables
     */
    public function list(Request $request)
    {
        $risk_profiles = q_risk_profiles($request->uker_id);

        $data = RiskControl::select('risk_controls.id', 'risk_controls.risk_statement_id', 'risk_controls.control', 'risk_controls.satisfy', 'risk_controls.possibility', 'risk_controls.impact', 'risk_controls.priority')
            ->joinSub($risk_profiles, 'profiles', function ($join) {
                $join->on('profiles.id', '=', 'risk_controls.risk_profile_id');
            })->orderBy('risk_controls.risk_statement_id', 'asc')
            ->get();

        return DataTables::of($data)
            ->editColumn('possibility', function ($data) {
                return lbl_possibility($data->possibility);
            })
            ->editColumn('impact', function ($data) {
                return lbl_impact($data->impact);
            })
            ->addColumn('action', function ($data) {
                return act_button(['edit', 'delete'], '/risk/control/', $data->id);
            })
            ->addColumn('risk_statement', function ($data) {
                return $data->risk_statement->risk_statement;
            })
            ->addColumn('st_possibility', function ($data) {
                return lbl_possibility($data->risk_statement->possibility);
            })
            ->addColumn('st_impact', function ($data) {
                return lbl_impact($data->risk_statement->impact);
            })
            ->addColumn('st_risk', function ($data) {
                return btn_risk_cluster($data->risk_statement->possibility, $data->risk_statement->impact);
            })
            ->addColumn('risk_level', function ($data) {
                return btn_risk_cluster($data->possibility, $data->impact);
            })
            ->addColumn('memadai', function ($data) {
                if ($data->satisfy == 1) {
                    return 'Memadai';
                } else {
                    return 'Belum';
                }
            })
            ->addIndexColumn()
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $risk_statement = RiskStatement::whereIn('id', $request->statement_id)->get();

        foreach ($risk_statement as $statement) {
            RiskControl::create([
                'risk_profile_id' => $statement->risk_profile_id,
                'risk_statement_id' => $statement->id,
                'possibility' => $statement->possibility,
                'impact' => $statement->impact,
                'score' => $statement->score,
                'priority' => $statement->priority
            ]);
        }

        return redirect(route('control.index'))->with('success', show_message('save'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = $this->page_title;
        $page_description = 'edit data';
        $data = RiskControl::find($id);
        $possibilities = Possibility::full_title();
        $impacts = Impact::full_title();

        return view('pages.risk.control.form', compact('page_title', 'page_description', 'data', 'possibilities', 'impacts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $images = $request->file('images');
        // dd($request->all(), $images);
        $validator = Validator::make($request->all(), $this->rules($request, false));
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Pengendalian Risiko tidak boleh kosong');
        }

        $update = RiskControl::find($id);
        $update->fill($request->all());
        $update->update();
        $uker_id = $update->risk_profile->management->parent->id ?? 1;

        return redirect(route('control.index', ['uker_id' => $uker_id]))->with('success', show_message('save'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $destroy = RiskControl::find($id);
        $destroy->delete();
        return redirect()->back()->with('success', show_message('delete'));
    }
}

app/Http/Controllers/Risk/ProfileController.php
<?php

namespace App\Http\Controllers\Risk;

use App\Http\Controllers\Controller;
use App\Models\Management;
use App\Models\RiskProfile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Datatables;

class ProfileController extends Controller
{
    private $page_title = 'Tujuan Kegiatan Utama';

    private function rules(Request $request, bool $isEdit)
    {
        $rules = [
            'semester' => 'required|integer',
            'number' => 'required|min:1|max:25',
            'target' => 'required|min:5|max:250',
            'indicator' => 'required|min:5|max:250',
            'activity' => 'required|min:5|max:250',
            'goal' => 'required|min:5|max:250',
        ];

        return $rules;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $uker_id = 1;
        if (isset($request->uker_id)) {
            $uker_id = $request->uker_id;
        }
        $page_title = $this->page_title;
        $page_description = 'list data -> Periode ' . period()->period;
        $uker = Management::pluck('title', 'id');

        return view('pages.risk.profile.index', compact('page_title', 'page_description', 'uker', 'uker_id'));
    }

    /**
     * Show the list of targets data.
     *
     * @return Yajra\Datatables\Datatables
     */
    public function list(Request $request)
    {
        $period_id = period()->id;
        $uker_id = $request->uker_id;
        $mng_id = Management::getIncludeID($uker_id);

        $data = RiskProfile::where('period_id', '=', $period_id)->whereIn('management_id', $mng_id)
            ->orderBy('management_id', 'asc')->orderBy('id', 'asc')->get();

        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return act_button(['edit', 'delete'], '/risk/profile/', $data->id);
            })
            ->addColumn('uker', function ($data) {
                return $data->management->title;
            })
            ->addIndexColumn()
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = $this->page_title;
        $page_description = 'tambah data';
        $data = [];
        $upr = Management::pluck('title', 'id');

        return view('pages.risk.profile.form', compact('page_title', 'page_description', 'data', 'upr'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), $this->rules($request, false));
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Data nomor, semester, dan tujuan harus terisi');
        }

        RiskProfile::create($request->all());

        return redirect(route('profile.index'))->with('success', show_message('save'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = $this->page_title;
        $page_description = 'tambah data';
        $data = RiskProfile::find($id);
        $upr = Management::pluck('title', 'id');

        return view('pages.risk.profile.form', compact('page_title', 'page_description', 'data', 'upr'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->rules($request, false));
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Data nomor, semester, dan tujuan harus terisi');
        }

        $update = RiskProfile::find($id);
        $update->fill($request->all());
        $update->update();
        $uker_id = $update->management->parent->id ?? 1;

        return redirect(route('profile.index', ['uker_id' => $uker_id]))->with('success', show_message('update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $destroy = RiskProfile::find($id);
        $destroy->delete();

        return redirect()->back()->with('success', show_message('delete'));
    }
}

resources/views/pages/risk/response/index.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')
    @include('pages.risk.modal._modal-statement')
    <!--begin::Card-->
    <div class="card card-custom">
        <!--begin::Header-->
        <div class="card-header">
            <div class="card-title">
                <label class="font-size-h4">Unit Pemilik Risiko (UPR):
                    {!! Form::select('upr', $uker, $uker_id, ['class' => 'form-control selectpicker', 'id'=>'uker']); !!}
                </label>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="#" class="btn btn-primary font-weight-bolder" data-toggle="modal" id="new_data">
                    <i class="fas fa-layer-group"></i>
                    Data Baru
                </a>
                <!--end::Button-->
            </div>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body">
            <!--begin: Datatable-->
            <div class="table-responsive">
                <table id="db_control" class="table table-bordered table-default" width="100%" cellspacing="0">
                    <thead class="thead-light">
                        <tr>
                            <th class="text-center align-middle" rowspan="2">No</th>
                            <th rowspan="2" class="align-middle">Pernyataan Risiko</th>
                            <th colspan="3" class="text-center">Risiko Pengendalian</th>
                            <th rowspan="2" class="align-middle">Respon</th>
                            <th rowspan="2" class="align-middle">Inovasi</th>
                            <th rowspan="2" class="align-middle">Alokasi SD</th>
                            <th colspan="4" class="text-center">Risiko Respon</th>
                            <th class="text-center align-middle" rowspan="2" style="min-width: 70px"><i class="fas fa-cog"></i></th>
                        </tr>
                        <tr>
                            <th class="text-center" style="cursor:pointer" title="Kemungkinan">K</th>
                            <th class="text-center" style="cursor:pointer" title="Dampak">D</th>
                            <th class="text-center" style="cursor:pointer" title="Tingkat Risiko">Ri</th>

                            <th class="text-center" style="cursor:pointer" title="Kemungkinan">K</th>
                            <th class="text-center" style="cursor:pointer" title="Dampak">D</th>
                            <th class="text-center" title="Nilai Risiko">N</th>
                            <th class="text-center" style="cursor:pointer" title="Tingkat Risiko">Ri</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!--end: Datatable-->
        </div>
        <!--end::Body-->
    </div>
    <!--end::Card-->
    {!! Form::open(['url' => route('response.store'), 'id' => 'form_create']) !!}
    {!! Form::close() !!}
@endsection

@section('styles')
<link href="{{ asset('plugins/custom/datatables/datatables.bundle.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('scripts')
<script src="{{ asset('plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script>
    var table_control = $('#db_control').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        // searching: false,
        // ordering: false,
        // paging: false,
        ajax: {
            type: 'POST',
            url: '{{ route("response.list") }}',
            dataType: 'json',
            data: {
                _token: "{{ csrf_token() }}",
                uker_id: function() { return $('#uker').find(':selected').val(); },
            },
        },
        rowId: 'id',
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', class:"text-center"},
            {data: 'risk_statement', name: 'risk_statement'},
            {data: 'st_possibility', name: 'st_possibility', class:"text-center"},
            {data: 'st_impact', name: 'st_impact', class:"text-center"},
            {data: 'st_risk', name: 'st_risk', class:"text-center"},

            {data: 'response', name: 'response'},
            {data: 'innovation', name: 'innovation'},
            {data: 'resource', name: 'resource'},

            {data: 'possibility', name: 'possibility', class:"text-center"},
            {data: 'impact', name: 'impact', class:"text-center"},
            {data: 'priority', name: 'priority', class:"text-center"},
            {data: 'risk_level', name: 'risk_level', class:"text-center"},

            {data: 'action', name: 'action', class:"text-center"}
        ],
        language: {
            emptyTable: "Data tidak tersedia"
        },
        columnDefs: [
            { orderable: true, className: 'reorder', targets: 10 },
            { orderable: false, targets: '_all' }
        ],
        // dom: 'frtp',
        buttons: [
            'print', 'excel', 'pdf', 'copy', 'csv' 
        ],
    });

    $('#uker').on('change', function(){
        table_control.draw();
    });

    var table_statement = $('#db_statement').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        // searching: false,
        // ordering: false,
        // paging: false,
        ajax: {
            type: 'POST',
            url: '{{ route("statement.list") }}',
            dataType: 'json',
            data: {
                _token: "{{ csrf_token() }}",
                uker_id: function() { return $('#uker').find(':selected').val(); },
                risk_from: 'respon',
            },
        },
        rowId: 'id',
        columns: [
            {data: null, defaultContent: '', class: 'select-checkbox'},
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'risk_statement', name: 'risk_statement'},
            {data: 'category', name: 'category'},
            {data: 'reason', name: 'reason'},
            {data: 'possibility', name: 'possibility', class:"text-center"},
            {data: 'impact', name: 'impact', class:"text-center"},
            {data: 'priority', name: 'priority', class:"text-center"},
            {data: 'risk_level', name: 'risk_level', class:"text-center"},
        ],
        language: {
            emptyTable: "Data tidak tersedia"
        },
        select: {
            style:    'os',
            selector: 'td:first-child'
        },
        columnDefs: [
            { orderable: true, className: 'reorder', targets: 7 },
            { orderable: false, targets: '_all' },
        ],
    });

    function select_statement()
    {
        // var data = table_statement.rows({ selected: true }).data();
        var data = table_statement.rows({ selected: true }).ids();
        if (data.length > 0) {
            for (let i = 0; i < data.length; i++) {
                $('#form_create').append('<input name="statement_id[]" type="hidden" value="' + data[i] + '">');
            }
            $('#modal_statement').modal('hide');
            $('#form_create').submit();
        } else {
            Swal.fire("", "Belum ada data terpilih", "info");
        }
    }

    $('#new_data').on('click', function() {
        event.preventDefault();
        $('#modal_statement').modal('show');
    })
</script>
@endsection