routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['reset' => false, 'verify' => false]);

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    // group menu resiko
    Route::prefix('risk')->group(function () {
        Route::post('/profile/list', 'Risk\ProfileController@list')->name('profile.list');
        Route::resource('profile', Risk\ProfileController::class);

        Route::post('/statement/tmp_list', 'Risk\StatementController@tmp_list')->name('statement.tmp_list');
        Route::post('/statement/list', 'Risk\StatementController@list')->name('statement.list');
        Route::resource('statement', Risk\StatementController::class);

        Route::post('/control/list', 'Risk\ControlController@list')->name('control.list');
        Route::resource('control', Risk\ControlController::class);

        Route::post('/response/list', 'Risk\ResponseController@list')->name('response.list');
        Route::resource('response', Risk\ResponseController::class);
    });

    // group menu kendali mutu
    Route::prefix('control')->group(function () {
        Route::post('/employee/list', 'Control\EmployeeController@list')->name('employee.list');
        Route::resource('employee', Control\EmployeeController::class);

        Route::post('/auditan/list', 'Control\AuditanController@list')->name('auditan.list');
        Route::resource('auditan', Control\AuditanController::class);

        Route::post('/planning/list', 'Control\AuditPlanController@list')->name('planning.list');
        Route::resource('planning', Control\AuditPlanController::class);

        Route::post('/execution/list', 'Control\ExecutionController@list')->name('execution.list');
        Route::resource('execution', Control\ExecutionController::class);

        Route::post('/assigment/list', 'Control\AssigmentController@list')->name('assigment.list');
        Route::resource('assigment', Control\AssigmentController::class);

        Route::post('/report/list', 'Control\ReportController@list')->name('report.list');
        Route::resource('report', Control\ReportController::class);
    });

    // group menu setting
    Route::prefix('setting')->group(function () {
        Route::post('/period/set_active', 'Setting\PeriodController@set_active');
        Route::post('/period/list', 'Setting\PeriodController@list')->name('period.list');
        Route::resource('period', Setting\PeriodController::class);

        Route::post('/possibility/list', 'Setting\PossibilityController@list')->name('possibility.list');
        Route::resource('possibility', Setting\PossibilityController::class);

        Route::post('/impact/list', 'Setting\ImpactController@list')->name('impact.list');
        Route::resource('impact', Setting\ImpactController::class);

        Route::post('/category/list', 'Setting\CategoryController@list')->name('category.list');
        Route::resource('category', Setting\CategoryController::class);

        Route::post('/risk_impact/list', 'Setting\RiskImpactController@list')->name('risk_impact.list');
        Route::resource('risk_impact', Setting\RiskImpactController::class);

        Route::get('riskmap', 'Setting\RiskmapController@index')->name('riskmap.index');

        Route::get('/satker/list_tree', 'Setting\SatkerController@list_tree')->name('satker.list_tree');
        Route::resource('satker', Setting\SatkerController::class);

        Route::post('/stakeholder/list', 'Setting\StakeholderController@list')->name('stakeholder.list');
        Route::resource('stakeholder', Setting\StakeholderController::class);

        Route::post('/cluster/item', 'Setting\ClusterController@get_item');
        Route::post('/cluster/list', 'Setting\ClusterController@list')->name('cluster.list');
        Route::put('/cluster/{cluster}', 'Setting\ClusterController@update');

        Route::post('/user/list', 'Setting\UserController@list')->name('user.list');
        Route::resource('user', Setting\UserController::class);
    });
});

// Quick search dummy route to display html elements in search dropdown (header search)
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

app/Http/Controllers/Setting/CategoryController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    private $page_title = 'Kategori Risiko';

    private function rules()
    {
        $rules = [
            'title' => 'max:100',
            'description' => 'max:250',
        ];

        return $rules;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = $this->page_title;
        $page_description = 'list data';

        return view('pages.setting.category.index', compact('page_title', 'page_description'));
    }

    /**
     * Show the list of data.
     *
     * @return Yajra\Datatables\Datatables
     */
    public function list()
    {
        $data = Category::all();
        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return act_button(['edit', 'delete'], '/setting/category/', $data->id);
            })
            ->addIndexColumn()
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = $this->page_title;
        $page_description = 'tambah data';
        $data = [];

        return view('pages.setting.category.form', compact('page_title', 'page_description', 'data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), $this->rules());
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Data isian tidak sesuai');
        }

        Category::create($request->all());

        return redirect(route('category.index'))->with('success', show_message('save'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = $this->page_title;
        $page_description = 'edit data';
        $data = Category::find($id);

        return view('pages.setting.category.form', compact('page_title', 'page_description', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->rules());
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Data isian tidak sesuai');
        }

        $update = Category::find($id);
        $update->fill($request->all());
        $update->update();

        return redirect(route('category.index'))->with('success', show_message('update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $destroy = Category::find($id);
        $destroy->delete();
        return redirect()->back()->with('success', show_message('delete'));
    }
}

app/Http/Controllers/Setting/ClusterController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use App\Models\Cluster;
use App\Models\Score;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Str;

class ClusterController extends Controller
{
    /**
     * Show the list of data.
     *
     * @return Yajra\Datatables\Datatables
     */
    public function list()
    {
        $data = Cluster::all();
        return Datatables::of($data)
            ->addColumn('risk_level', function ($data) {
                $title = preg_replace('/(?<=\w)./', '', $data->name);
                $title = '<button type="button" class="btn btn-sm text-white font-weight-bold" data-toggle="tooltip" data-placement="top" style="background-color:' . $data->color . '">' . $title . '</button>';
                return Str::of($title)->toHtmlString();
            })
            ->addColumn('title', function ($data) {
                $title = '<button type="button" class="btn btn-sm text-white font-weight-bold" data-toggle="tooltip" data-placement="top" style="background-color:' . $data->color . '">' . $data->name . '</button>';
                return Str::of($title)->toHtmlString();
            })
            ->addColumn('action', function ($data) {
                $btn_edit = '<button class="btn btn-icon btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit Data" href="#" onclick="cluster_edit(' . $data->id . ')"><i class="fas fa-pencil-alt"></i></button>';
                return $btn_edit;
            })
            ->make(true);
    }

    public function update(Request $request, $id)
    {
        $update = Cluster::find($id);
        $update->name = $request->modal_name;
        $update->from = $request->modal_from;
        $update->to = $request->modal_to;
        $update->color = $request->modal_color;
        $update->update();

        Score::whereBetween('priority', [$request->modal_from, $request->modal_to])
            ->update(['cluster_id' => $id]);

        return redirect(route('riskmap.index'))->with('success', show_message('update'));
    }

    public function get_item(Request $request)
    {
        $score = risk_cluster($request->possibility_id, $request->impact_id);
        $data = $score->cluster->toArray();
        $data['priority'] = $score->priority;
        return response()->json($data);
    }
}

app/Http/Controllers/Setting/ImpactController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use App\Models\Impact;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Validator;

class ImpactController extends Controller
{
    private $page_title = 'Level Dampak';

    private function rules()
    {
        $rules = [
            'level' => 'required|numeric',
            'title' => 'max:100',
            'description' => 'max:250',
        ];

        return $rules;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = $this->page_title;
        $page_description = 'list data';

        return view('pages.setting.impact.index', compact('page_title', 'page_description'));
    }

    /**
     * Show the list of data.
     *
     * @return Yajra\Datatables\Datatables
     */
    public function list()
    {
        $data = Impact::all();
        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return act_button(['edit'], '/setting/impact/', $data->id);
            })
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = $this->page_title;
        $page_description = 'edit data';
        $data = Impact::find($id);

        return view('pages.setting.impact.form', compact('page_title', 'page_description', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->rules());
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Data isian tidak sesuai');
        }

        $update = Impact::find($id);
        $update->fill($request->all());
        $update->update();

        return redirect(route('impact.index'))->with('success', show_message('update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Setting/PossibilityController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use App\Models\Possibility;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Validator;

class PossibilityController extends Controller
{
    private $page_title = 'Kemungkinan Risiko';

    private function rules()
    {
        $rules = [
            'level' => 'required|numeric',
            'title' => 'max:100',
            'tolerance' => 'max:250',
            'percentage' => 'max:250',
            'frequency' => 'max:250',
        ];

        return $rules;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = $this->page_title;
        $page_description = 'list data';

        return view('pages.setting.possibility.index', compact('page_title', 'page_description'));
    }

    /**
     * Show the list of data.
     *
     * @return Yajra\Datatables\Datatables
     */
    public function list()
    {
        $data = Possibility::all();
        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return act_button(['edit'], '/setting/possibility/', $data->id);
            })
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = $this->page_title;
        $page_description = 'edit data';
        $data = Possibility::find($id);

        return view('pages.setting.possibility.form', compact('page_title', 'page_description', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->rules());
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', 'Data isian tidak sesuai');
        }

        $update = Possibility::find($id);
        $update->fill($request->all());
        $update->update();

        return redirect(route('possibility.index'))->with('success', show_message('update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Setting/RiskmapController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use App\Models\Cluster;
use App\Models\Score;

class RiskmapController extends Controller
{
    private $page_title = 'Peta Risiko';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = $this->page_title;
        $page_description = '';
        $chart_risk = Score::heat_series('priority');
        $chart_risk['title'] .= ' berdasar Prioritas';

        return view('pages.setting.riskmap.index', compact('page_title', 'page_description', 'chart_risk'));
    }
}

resources/views/pages/setting/management/_form.blade.php
<!--begin::Modal-->
<div class="modal fade" id="modal_agency" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Satuan Kerja</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <form id="form_agency" method="post" accept-charset="UTF-8" enctype="multipart/form-data" class="form-horizontal">
                @csrf
                <div class="modal-body">
                    <input type="hidden" name="parent_id" id="parent_id">
                    <input type="hidden" name="mng_level" id="mng_level">
                    <div class="form-group">
                        <label class="font-weight-bold">Satker Induk -> </label>
                        <span id="parent_title" class="font-weight-bold">#</span>
                    </div>
                    <div class="form-group">
                        <label>Satuan Kerja</label>
                        <input type="text" name="title" id="title" class="form-control"  placeholder="Satuan Kerja"/>
                    </div>
                    <div class="form-group">
                        <label>Pemilik Risiko</label>
                        <input type="text" name="owner_name" id="owner_name" class="form-control"  placeholder="Pemilik Risiko"/>
                        <input type="text" name="owner_position" id="owner_position" class="form-control"  placeholder="Jabatan Pemilik Risiko"/>
                    </div>
                    <div class="form-group">
                        <label>Pengelola Risiko</label>
                        <input type="text" name="manager_name" id="manager_name" class="form-control"  placeholder="Pengelola Risiko"/>
                        <input type="text" name="manager_position" id="manager_position" class="form-control"  placeholder="Jabatan Pengelola Risiko"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary font-weight-bold mr-2" onclick="save_satker();">Simpan</button>
                    <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Batal</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--end::Modal-->

resources/views/pages/setting/management/index.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')
    <!--begin::Card-->
    <div class="row">
        <div class="col-lg-6">
            <!--begin::Card-->
            <div class="card card-custom">
                <!--begin::Body-->
                <div class="card-body">
                    <div style="border: 1px solid rgb(204, 204, 204); padding: 5px; overflow: auto; width: 100%; max-height: 350px; background-color: rgb(255, 255, 255);">
                        <div id="tr_agency" class="tree-demo">
                        </div>  
                    </div>
                    <div class="card-toolbar text-right py-5">
                        <div class="dropdown dropdown-inline">
                            <a href="#" class="btn btn-primary font-weight-bold mr-2 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="flaticon2-plus-1"></i>Tambah</a>
                            <div class="dropdown-menu dropdown-menu-md py-5">
                                <ul class="navi navi-hover">
                                    <li class="navi-item">
                                        <a class="navi-link" href="#" onclick="add_satker()">
                                            <span class="navi-icon"><i class="fas fa-home text-primary"></i></span>
                                            <span class="navi-text">Satker</span>
                                        </a>
                                    </li>
                                    <li class="navi-item">
                                        <a class="navi-link" href="#" onclick="add_satker(false)">
                                            <span class="navi-icon"><i class="fas fa-house-user text-primary"></i></span>
                                            <span class="navi-text">Sub Satker</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <a href="#" class="btn btn-primary font-weight-bold mr-2" onclick="edit_satker()"><i class="flaticon-edit"></i>Edit</a>
                        <a href="#" class="btn btn-warning font-weight-bold" onclick="del_satker()"><i class="flaticon2-rubbish-bin"></i>Delete</a>
                    </div>
                </div>
                <!--end::Body-->
            </div>
            <!--end::Card-->
        </div>
        <div class="col-lg-6">
            <!--begin::Card-->
            <div class="card card-custom">
                <!--begin::Body-->
                <div class="card-body">
                    <div class="form-group">
                        <label>Satuan Kerja</label>
                        <input type="text" readonly id="node_title" class="form-control"  placeholder="Satuan Kerja"/>
                    </div>
                    <div class="form-group">
                        <label>Pemilik Risiko</label>
                        <input type="text" readonly id="node_owner" class="form-control"  placeholder="Pemilik Risiko"/>
                        <input type="text" readonly id="node_owner_position" class="form-control"  placeholder="Jabatan Pemilik Risiko"/>
                    </div>
                    <div class="form-group">
                        <label>Pengelola Risiko</label>
                        <input type="text" readonly id="node_manager" class="form-control"  placeholder="Pengelola Risiko"/>
                        <input type="text" readonly id="node_manager_position" class="form-control"  placeholder="Jabatan Pengelola Risiko"/>
                    </div>
                </div>
                <!--end::Body-->
            </div>
            <!--end::Card-->
        </div>
    </div>
    <!--end::Card-->
    @include('pages.setting.management._form')
@endsection

@section('styles')
<link href="{{ asset('plugins/custom/jstree/themes/default/style.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('scripts')
<script src="{{ asset('plugins/custom/jstree/jstree.min.js') }}"></script>
<script>
    var node, node_parent;
    var set_mode = 'edit';
    var str_action = "{{ route('satker.store') }}";

    $('#tr_agency').jstree({
        'core' : {
            "themes": {
                "responsive": false
            },
            'data' : {
                "url" : "{{ route('satker.list_tree') }}",
                "dataType" : "json" // needed only if you do not supply JSON headers
            }
        },

    });

    $('#tr_agency').on("changed.jstree", function (e, data) {
        if (data.selected.length) {
            node = data.instance.get_node(data.selected[0]);
            node_parent = data.instance.get_node(node.parent);

            $('#node_title').val(node.text);
            $('#node_owner').val(node.a_attr['owner_name']);
            $('#node_owner_position').val(node.a_attr['owner_position']);
            $('#node_manager').val(node.a_attr['manager_name']);
            $('#node_manager_position').val(node.a_attr['manager_position']);
        }
    });

    function add_satker(is_satker = true)
    {
        var parent_level;
        if (is_satker) {
            // menambah satker
            if (node_parent.id == '#') {
                Swal.fire("", "Tidak dapat lagi menambah data pada level ini", "warning");
                return false;
            } else {
                $('#parent_id').val(node_parent.id);
                $('#parent_title').text(node_parent.text);
                parent_level = node_parent.a_attr['mng_level'];
            }
        } else {
            // menambah sub satker
            if (node.a_attr['mng_level'] < 2) {
                $('#parent_id').val(node.id);
                $('#parent_title').text(node.text);
                parent_level = node.a_attr['mng_level'];
            } else {
                Swal.fire("", "Tidak dapat lagi menambah sub data pada level ini", "warning");
                return false;
            }
        }
        set_mode = 'add';

        $('.modal-title').html('Tambah Satuan Kerja');
        $('#mng_level').val(parent_level+1);
        $('#title').val('');
        $('#owner_name').val('');
        $('#owner_position').val('');
        $('#manager_name').val('');
        $('#manager_position').val('');
        $('#modal_agency').modal('show');
    }

    function edit_satker()
    {
        if (node_parent.id != '#') {
            $('#parent_title').text(node_parent.text);
        } else {
            $('#parent_title').text('#');
        }
        $('#parent_id').val(node_parent.id);
        set_mode = 'edit';

        $('.modal-title').html('Edit Satuan Kerja');
        $('#mng_level').val(node.a_attr['mng_level']);
        $('#title').val(node.text);
        $('#owner_name').val(node.a_attr['owner_name']);
        $('#owner_position').val(node.a_attr['owner_position']);
        $('#manager_name').val(node.a_attr['manager_name']);
        $('#manager_position').val(node.a_attr['manager_position']);

        $('#modal_agency').modal('show');
    }

    function save_satker() {
        if (set_mode == 'edit') {
            $('#form_agency').prepend('<input type="hidden" name="_method" value="PUT">');
            $('#form_agency').prop('action', str_action + '/' + node.id);
        } else {
            $('#form_agency').prop('action', str_action);
        }
        $('#form_agency').submit();
    }

    function del_satker() {
        if (node.children.length == 0) {
            Swal.fire({
                text: "Apakah anda yakin untuk menghapus data ini?",
                icon: "warning",
                showCancelButton: true,
                cancelButtonText: "Batal",
                confirmButtonText: "Ya, Hapus!"
            }).then(function(result) {
                if (result.value) {
                    $('#form_agency').prepend('<input type="hidden" name="_method" value="DELETE">');
                    $('#form_agency').prop('action', str_action + '/' + node.id);
                    $('#form_agency').submit();
                }
            });
            return false;
        } else {
            Swal.fire("", "Data tidak dapat dihapus, karena punya sub-data", "warning");
        }
    }
</script>
@endsection